steps:
  # Membangun Docker image dari folder backend
  - name: "gcr.io/cloud-builders/docker"
    dir: "backend"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/backend", "."]

  # Push Docker image ke Google Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/backend"]

  # Deploy ke Cloud Run menggunakan image yang sudah di-push
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "backend",
        "--image",
        "gcr.io/$PROJECT_ID/backend",
        "--timeout",
        "1000s",
        "--port",
        "5000", # Sesuaikan dengan port di index.js
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
