steps:
  # STEP 1: Membangun Docker image dari folder backend
  # -----------------------------------------------
  # - name: image builder docker dari GCP
  # - dir: menunjukkan direktori tempat Dockerfile berada
  # - args: perintah docker build -t <nama-image> .
  - name: "gcr.io/cloud-builders/docker"
    dir: "backend"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/backend", "."]

  # STEP 2: Mengunggah Docker image ke Google Artifact Registry
  # -----------------------------------------------
  # - args: perintah docker push ke registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/backend"]

  # STEP 3: Deploy ke Cloud Run
  # -----------------------------------------------
  # - name: menggunakan gcloud CLI tool
  # - args: perintah untuk deploy service Cloud Run
  # - --image: gunakan image yang sudah di-push ke Artifact Registry
  # - --port: port aplikasi di dalam container (harus match dengan EXPOSE di Dockerfile dan listen di Express)
  # - --region: region tempat Cloud Run akan dideploy
  # - --allow-unauthenticated: agar bisa diakses publik (tanpa login)
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "backend",                          # nama service di Cloud Run
        "--image",
        "gcr.io/$PROJECT_ID/backend",      # URL image dari Artifact Registry
        "--timeout",
        "1000s",                            # waktu maksimal build (opsional)
        "--port",
        "5000",                             # sesuai dengan app.listen() di index.js
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

# Opsional: hanya logging ke Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY
